### ISSUE TITLE
Remote nodes workflow

### ISSUE THREAD

**Issue by krzysztofantczak** [olevole/cbsd#38]
Hello again.

I'm trying to figure out what's your workflow with jails on remote nodes? It's kind of hard to understand it from the docs. For example, what's the simplest way of performing similar to local operations on remote node (create, export, etc.)?

**Comment by krzysztofantczak** [comment]
Also

```
cbsd node mode=add node=10.0.1.71 pw=cbsd port=22
Connecting to 10.0.1.71...
10.0.1.71 has nodename: node1.test
Added successfull: 10.0.1.71
Already exist in database, updating: 10.0.1.71
CBSD: Fetching inventory done: node1. test
```

and

```
root@master:/vagrant # cbsd node mode=list
NODENAME          IP         PORT  KEYFILE                                                   STATUS        IDLE
node1. test  10.0.1.71  22    /usr/jails/.rssh/678051e3f9229bfac42efde597820630.id_rsa  Disconnected  0
```
any ideas what 'disconnected' status means? what's missing?

**Comment by krzysztofantczak** [comment]
Also, it seems i have some problem with permanently disconnected nodes:

```
root@master:/vagrant # cbsd node mode=list
NODENAME          IP         PORT  KEYFILE                                                   STATUS        IDLE
node1.racker.sys  10.0.1.71  22    /usr/jails/.rssh/678051e3f9229bfac42efde597820630.id_rsa  Disconnected  6
node2.racker.sys  10.0.1.72  22    /usr/jails/.rssh/14223feb6ddbdf51c30e9c0747e5ab86.id_rsa  Disconnected  6
```
and
```
root@master:/vagrant # cbsd jstart jname=proxy1 node=node1.racker.sys
Remote jstart: proxy1 on node1.racker.sys
Node is offline: node1.racker.sys
```

They were online for a short while, now it's disconnected, any idea why is that?

**Comment by olevole** [comment]
1)
At the moment, the only use of added nodes - is an opportunity to get a list of jails on the farm without having to go to each:
~~~
cbsd jls alljails=1 shownode=1
~~~
 and remote entry into the jail.

In addition, 10.1.2 should be elementary notification system (as I did this as a test) - if you start or stop a jail at the remote node, the local node must receive status change very rapidly via
~~~
cbsd jls alljails = 1
~~~
Also, the jailscp command has to work - copying files to/from remote jails.
Of course, if you have root access through the key, nothing prevents to create jail on  remote node (but not yet by means of local cbsd):
~~~
cbsd rexe node=node2.racker.sys cbsd jconstruct-tui
~~~ 

2)
About offline status. Do the same version of CBSD on both servers?

This can happen when two different versions of CBSD or you have not rebooted the server after the upgrade CBSD (I have had some changes in establishing a connection in 10.1.2 version)

Likely to help reload cbsdd (not restart):
~~~
service cbsdd reload
~~~
Or - if CBSD was update and you can restart the node - it is better to try to do it.

**Comment by krzysztofantczak** [comment]
ad1. it would be nice to have jimport working with nodes but i guess i can just send img file and import locally.
ad2. master and both nodes are fresh vagrant setups with cbsd cloned from git (master branch)
reloading cubs on node1:
```
root@node1:/vagrant # service cbsdd reload
No ALTQ support in kernel
ALTQ related functions disabled
No ALTQ support in kernel
ALTQ related functions disabled
pfctl: pf already enabled
Starting cbsdd.
root@node1:/vagrant # cbsd runtask 1/1 (10 max)
```
didn't helped

reloading on master:
```
root@master:/vagrant # service cbsdd reload
No ALTQ support in kernel
ALTQ related functions disabled
No ALTQ support in kernel
ALTQ related functions disabled
pfctl: pf already enabled
Starting cbsdd.
root@master:/vagrant # CBSD: Fetching inventory done: node1.racker.sys
cbsd runtask 1/1 (10 max)
cbsd runtask 1/1 (10 max)
CBSD: Fetching inventory done: node2.racker.sys
```

also didn't helped:
```
root@master:/vagrant # cbsd node mode=list
NODENAME          IP         PORT  KEYFILE                                                   STATUS        IDLE
node1.racker.sys  10.0.1.71  22    /usr/jails/.rssh/678051e3f9229bfac42efde597820630.id_rsa  Disconnected  0
node2.racker.sys  10.0.1.72  22    /usr/jails/.rssh/14223feb6ddbdf51c30e9c0747e5ab86.id_rsa  Disconnected  0
```

But it seems IDLE time was reseted.

**Comment by olevole** [comment]
Instead of jimport from/to remote node, you can use jrclone:
~~~
cbsd jrclone node=node2.racker.sys jname=XXXX
~~~
If jrclone not fit - can be described in more detail with the idea jimport? I am interested in any of the needs of those who use FreeBSD/jail and can empower cbsd.

Question about status:
If you are using a version from git - have you a symlink from rc.d ?
~~~
readlink /usr/local/etc/rc.d/cbsdd 
~~~

Also, if there is a symlink, maybe you change the key (for example, nodename change) ? You can try to add the node again through
~~~
cbsd node mode=add node=XXXX
~~~

**Comment by krzysztofantczak** [comment]
Ad 'jimport' - in that case i'll try to open another ticker for it. And about status, yes i have symlink:
```
root@node1:/vagrant # readlink /usr/local/etc/rc.d/cbsdd
/usr/jails/rc.d/cbsdd
```
about adding node again - i've already tried multiple times but yet again:
```
root@master:/vagrant # !210
cbsd node mode=add node=10.0.1.72 pw=cbsd port=22
Connecting to 10.0.1.72...
10.0.1.72 has nodename: node2.racker.sys
Added successfull: 10.0.1.72
Already exist in database, updating: 10.0.1.72
cCBSD: Fetching inventory done: node2.racker.sys
```
and
```
bsd root@master:/vagrant # cbsd node mode=list
NODENAME          IP         PORT  KEYFILE                                                   STATUS        IDLE
node1.racker.sys  10.0.1.71  22    /usr/jails/.rssh/678051e3f9229bfac42efde597820630.id_rsa  Disconnected  684
node2.racker.sys  10.0.1.72  22    /usr/jails/.rssh/14223feb6ddbdf51c30e9c0747e5ab86.id_rsa  Disconnected  0
```

**Comment by olevole** [comment]
Paste where you have permission - is yet normal state, this operation requires root privileges. I now have a very limited number of commands for drop to root (see sudoexec directory). 

> What part of cbsd is responsible for that connection?

This is a common permanent ssh connection by using external ssh command and run it from $workdir/tools/cbsdd script. In this case, also it use ~cbsd/.ssh/config which is registered SocketMaster for multiplexing other compounds - that significantly speeds up the command, because there is no long handshake when installing ssh connection.

Determination that the remote node is available, going through the checkout lock file that is created when you install the master-connection:
~~~
% ls ~cbsd/ftmp/shmux*
~~~

on the remote node executed "cbsd dot" script - current notification mechanism: this script monitors the changes via kqueue for SQLite database, and if it is refreshed - provides an indication that it is necessary to take a base. Now this realization made as plug - I'm still in search of good solutions (eg based on AMQP messages like ZMQ +google protobu f/message pack or something like that).

**Comment by krzysztofantczak** [comment]
Ok, nodes are still 'disconnected', and yet it seems i've screwed whole cbsd installation on all nodes - including master. I need to revert whole vagrant setup.

**Comment by krzysztofantczak** [comment]
Ok, a bit more debugging (nodes were online in about 5 minutes, and now they are "disconnected" again).

```
root@master:/vagrant # ps aux | grep cbsd
cbsd     7054   0.0  0.1  14396   288  -  Ss    9:33AM    0:00.10 /usr/jails/misc/daemon -u cbsd /usr/bin/lockf -s -t0 /usr/jails/ftmp/shmux_10.0.1.72.lock /usr/bin/ssh -oControlPersist=30m -oBatchMode=yes -oStrictHostKeyCh
cbsd     7056   0.0  0.1  14396   288  -  Ss    9:33AM    0:00.10 /usr/jails/misc/daemon -u cbsd /usr/bin/lockf -s -t0 /usr/jails/ftmp/shmux_10.0.1.71.lock /usr/bin/ssh -oControlPersist=30m -oBatchMode=yes -oStrictHostKeyCh
cbsd     7057   0.0  0.0   8164     0  -  IW   -          0:00.00 (lockf)
cbsd     7058   0.0  0.0   8164     0  -  IW   -          0:00.00 (lockf)
cbsd     7059   0.0  0.1  52176   492  -  I     9:33AM    0:00.03 /usr/bin/ssh -oControlPersist=30m -oBatchMode=yes -oStrictHostKeyChecking=no -oConnectTimeout=5 -q -oPort=22 -i /usr/jails/.rssh/14223feb6ddbdf51c30e9c0747e5
cbsd     7060   0.0  0.1  52176   492  -  I     9:33AM    0:00.02 /usr/bin/ssh -oControlPersist=30m -oBatchMode=yes -oStrictHostKeyChecking=no -oConnectTimeout=5 -q -oPort=22 -i /usr/jails/.rssh/678051e3f9229bfac42efde59782
cbsd     7064   0.0  0.2  52176  1020  -  Ss    9:33AM    0:01.28 ssh: /usr/jails/.ssh/sockets/cbsd@10.0.1.72:22 [mux] (ssh)
cbsd     7066   0.0  0.2  52176  1008  -  Ss    9:33AM    0:01.27 ssh: /usr/jails/.ssh/sockets/cbsd@10.0.1.71:22 [mux] (ssh)
root     6062   0.0  0.2  22224   932  0- I     9:25AM    0:00.99 /usr/local/bin/cbsd /usr/jails/tools/cbsdd
root     9239   0.0  0.2  22224   916  0- I     9:48AM    0:00.94 /usr/local/bin/cbsd /usr/jails/tools/cbsdd
root    13431   0.0  0.2  22224   916  0- I     9:53AM    0:00.85 /usr/local/bin/cbsd /usr/jails/tools/cbsdd
root    19152   0.0  0.2  22224   932  0- I    10:10AM    0:00.71 /usr/local/bin/cbsd /usr/jails/tools/cbsdd
root    21538   0.0  0.2  22224   932  0- I    10:11AM    0:00.67 /usr/local/bin/cbsd /usr/jails/tools/cbsdd
root    29604   0.0  0.2  22224   952  0- I    10:38AM    0:00.50 /usr/local/bin/cbsd /usr/jails/tools/cbsdd
root    32295   0.0  0.2  22224   952  0- I    10:38AM    0:00.50 /usr/local/bin/cbsd /usr/jails/tools/cbsdd
root    51485   0.0  0.6  22224  2956  1  I    11:24AM    0:00.05 /usr/local/bin/cbsd /usr/jails/tools/cbsdd
root    52986   0.0  0.3  18724  1728  1  S+   11:26AM    0:00.00 grep cbsd
```

also

```
root@master:/vagrant # ls ~cbsd/ftmp/shmux*
ls: No match.
```
(it was working when nodes were "online"), and what's really bugging me is the number of cbsdd processes from above, is it normal? btw. how many nodes are You using in your setup and how reliable is your connection from/to master to/from nodes?

**Comment by olevole** [comment]
With a duplicate process - it is not a normal situation. I'm going to test this functionality more after the holidays. In my test environment now 5 nodes. Unfortunately, at the moment I did not have job with FreeBSD where they could be tested on a large farm.

**Comment by krzysztofantczak** [comment]
Ok, great. If i get enough time i'll try to create some github repository with my test env setup (which is vagrant + few shell scripts and ansible config), so - if You're interested - could test in similar env as mine.

**Comment by olevole** [comment]
Cool, I'm curious to see how you use cbsd and valgrant

**Comment by krzysztofantczak** [comment]
Sure, and while creating that repo (it will be hosted here https://github.com/tradero/vac) i'll report few issues to CBSD repo that can be ignored until VAC repo is ready, since i don't think You'll hit them when using CBSD 'by the book'.

**Comment by krzysztofantczak** [comment]
Hey, repo is ready, it's not perfect, but this problem is reproducible there.

**Comment by olevole** [comment]
_Cleanup/close old issues._
I think the first (as prototype;  dirty and fast in implementation) interaction between nodes is a bit outdated and poor. In the next version I plan to use AMQM solutions for nodes workflow. But it requires a serious/hard work ;-). So I have to close this ticket as not relevant anymore.
