### ISSUE TITLE
Jail IPv6 Address

### ISSUE THREAD

**Issue by eraserewind** [olevole/cbsd#42]
Hi,

How to assign an IPv6 address to a jail ? (in complement of an IPv4 address).

I've tried to jset `ip6_addr` but it doesn't work.

Thanks

**Comment by olevole** [comment]
Use ip4_addr ;-) field for sets IPv6. 

is "ip4_addr" name historically, however, cbsd handles the address type

**Comment by eraserewind** [comment]
Ahaha, ok :-P

So i've tried:

```
cbsd@cyclone> jset jname=phantom ip4_addr "10.66.69.2/24 2001:bc8:360b:4242::80"
ifconfig: interface not ip does not exist
ip4_addr: ip4_addr
cbsd@cyclone> jget jname=phantom ip4_addr
ip4_addr: 10.66.69.2/24
```

I guess this because the IPv6 is on another interface (`bge0`) than the jail network (which is on `lo1`). When i'm adding the IPv6 using `jil -m ip6.addr="…"` it works fine.

**Comment by olevole** [comment]
use ',' as delimer for aliases. eg:
"192.168.0.2/24,10.0.0.2/16"

**Comment by olevole** [comment]
also for jset you need arg=val construction:

cbsd jset jname=xxx ip4_addr=""

or use
cbsd jconfig


-------- Исходное сообщение --------
Отправитель:Jordan <notifications@github.com>
Отправленные:Sun, 05 Apr 2015 16:24:50 +0400
Получатель:olevole/cbsd <cbsd@noreply.github.com>
Копия:Oleg Ginzburg <olevole@olevole.ru>
Тема:Re: [cbsd] Jail IPv6 Address (#42)

**Comment by eraserewind** [comment]
Oh! Yes, thanks. But it's still not working, because IPv6 (public) is on `bge0` but the jail network (private) is on `lo1`:

```
ifconfig: ioctl (SIOCAIFADDR): File exists
jail: phantom: /sbin/ifconfig lo1 inet6 2001:bc8:360b:4242::80 prefixlen 128 alias: failed
```

Should I use a script instead at the jail start ?

**Comment by olevole** [comment]
Hm, you try to set IP4 on lo0 and IPv6 on bge0 ? at present in the automatic mode there is no opportunity to create ip by CBSD on multiple interfaces, all IP and aliaseses are created on one.

Nevertheless, if you really want to use CBSD and to have jail on several interfaces, initialize these IP addresses in system (e.g via rc.conf), and in the jail settings deliver to interface=disable that CBSD didn't operate installation and removal of ip at start and a stop of a jail. For example, in rc.conf:

ifconfig_lo0_alias="10.66.69.2/24"
ipv4_addrs_igb0="2001:bc8:360b:4242::80"
ipv6_activate_all_interfaces="YES"

And in "cbsd jconfig jname=XXX" choose "interface" and set "disable".
PS: ip4_addr for jail without changes: "10.66.69.2/24,2001:bc8:360b:4242::80/64"
