### ISSUE TITLE
cbsd jconstruct-tui can't set the ver

### ISSUE THREAD

**Issue by beyondcreed** [olevole/cbsd#43]
Hello,

it seems ver cannot be set to something like 10.0, it always forces 10.1-RELEASE as we need to have different releases available in multiple jails.

when we set 10.0 it does

Please wait: this will take a while...
Applying skel dir template from: /usr/local/jails/share/FreeBSD-jail-skel
First running pkg. Bootstrapping...
pkg: [bootstrap...Ok]
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01    
Fetching packagesite.txz: 100%    5 MiB   5.3MB/s    00:01    
Processing entries: 100%
FreeBSD repository update completed. 23912 packages processed.

To edit jail properties use: cbsd jconfig jname=api3
Creating api3 complete: Enjoy!

then we cbsd start api3 and cbsd jlogin api3 just to see

FreeBSD 10.1-RELEASE (GENERIC) #0 r274401: Tue Nov 11 21:02:49 UTC 2014

which is not the correct version, any ideas?

**Comment by olevole** [comment]
Can you provide result of this command in master node:

mount -t nullfs |grep jails

And this one, inside jail (after jlogin):

file -s /bin/sh

**Comment by olevole** [comment]
Update:

Support  for kernel version spoofed was intoduced in FreeBSD 11-HEAD: https://svnweb.freebsd.org/base?view=revision&revision=r279361

FreeBSD versions before r279361 and CBSD <10.1.5 will display version of your node - it is FreeBSD issue. However, CBSD is to mount the correct version of the base - you can see it in the commands that I have written before. In addition, further, CBSD in make.conf file uses some workaround described in
~~~
grep -A28 ^20140930 /usr/ports/CHANGES
~~~
