### ISSUE TITLE
cbsd jconstruct-tui

### ISSUE THREAD

**Issue by mlotekk** [olevole/cbsd#46]
When I create jail using the jconstruct-tui I got error "No such emulator: 0". I can start and stop it but can't jlogin. The same error appears

**Comment by olevole** [comment]
What version you use? If it version from github, try this:

~~~
sqlite3 ~cbsd/var/db/local.sqlite 'UPDATE jails SET emulator="jail" WHERE emulator="0"'
~~~

This is instruction from
/usr/local/cbsd/upgrade/pre-patch-10.1.5.1

which had to be applied at "cbsd initenv" when you upgrade CBSD

**Comment by mlotekk** [comment]
I am using version from github. After updating database everything works. But cbsd jconstruct-tui creates new jail with variable emulator set to "0"

**Comment by olevole** [comment]
perhaps you forgot to execute:
~~~
cbsd initenv
~~~

it needs to be done after each updating of CBSD

**Comment by mlotekk** [comment]
I ran this command. Yet when I create a new prison creates it with variable emulator = 0.
I tried fresh install. I removed /usr/jails and /usr/local/cbsd and I installed cbsd again using the instructions on the page http://www.bsdstore.ru/en/installing_cbsd.html. Even after that the problem remains.

**Comment by olevole** [comment]
Can you update code from github and repeat this steps?

**Comment by mlotekk** [comment]
It looks like it works :+1:. I do not mind against errors. After all it is a test version. 
ps. this is the best software to manage a jails

**Comment by olevole** [comment]
Thanks!
