### ISSUE TITLE
NFR portsup feedback

### ISSUE THREAD

**Issue by ruudboon** [olevole/cbsd#48]
When doing cbsd portsup nothing is reported on the cmd-line.
Looking at the process I do see that svnlite is running but it takes a few minutes before something is shown.
Is it possible to add some progress feedback when portsup is running?

**Comment by olevole** [comment]
I'm not sure that we can show a progress for this operation because execution of 'svnlite' or 'svn' is atomic operation for me/scripts. Such delay is specific for svn - at this point it is an internal data processing. Perhaps it makes sense to display some message like 'In progress, please wait..'

**Comment by olevole** [comment]
Added reason for the delay before output: 
https://github.com/olevole/cbsd/commit/3351003a63dd9ec23e989fb1b6d83b719a2b7cfa

Thanks for the tip
