### ISSUE TITLE
Images backward compatibility

### ISSUE THREAD

**Issue by krzysztofantczak** [olevole/cbsd#50]
Hey,

It seems, that images from previous release are not working properly with new version of CBSD (here, at least), can You confirm that? The issue i had yesterday looked weird. As far as i was able to import "base" image (clean jail exported to .img) it seemed to be "detached" from cbsd. Like i was able to see it up and running under `jls` but there was no jails under `cbsd jls`. Now i have new "base" image, import works as expected. It took me a while to understand what's going on here.

**Comment by olevole** [comment]
Hello! I'm sorry, unfortunately I can not quite find the time for make support the old image format. I hope number of images is little). The best solution to get data from old images: install CBSD < 10.1 version then import data.  Closes the ticket as outdated.
