### ISSUE TITLE
Use existing buildworld result from base system

### ISSUE THREAD

**Issue by jnbek** [olevole/cbsd#52]
I build my own source tree and think it'd be a good idea to be able to have the option to have cbsd installworld install from this tree, instead of having to do a separate buildworld for cbsd nodes.

**Comment by olevole** [comment]
Good idea.

Currently you can use buildworld from local machine only by hands, e.g from /usr/src:
~~~
mkdir ~cbsd/basejail/base_`uname -m`_`uname -m`_`uname -r|cut -d - -f 1`
make -C /usr/src installworld DESTDIR=~cbsd/basejail/base_`uname -m`_`uname -m`_`uname -r|cut -d - -f 1`
~~~

and apply some CBSD-specific post-install action:
~~~
cbsd preparebase dst=~cbsd/basejail/base_`uname -m`_`uname -m`_`uname -r|cut -d - -f 1`
~~~

on my system (FreeBSD 11 amd64)
~~~
~cbsd/basejail/base_`uname -m`_`uname -m`_`uname -r|cut -d - -f 1` 
~~~

extracted to /usr/jails/basejail/base_amd64_amd64_11.0
And yes, perhaps it makes sense to me to make this operation separate command.

So i've leave this issue in open state for next release.

PS: On the other hand, you can setup your own repo for base.txz and change repo source from http://www.bsdstore.ru to yours for other nodes.

**Comment by olevole** [comment]
(within 79c51fe ): Implement populate base from current system. No source tree or object file needed. This work only if the version of container == base system version
