### ISSUE TITLE
jails-fstab files disappear when stopping and/or starting the cbsdd daemon

### ISSUE THREAD

**Issue by jnbek** [olevole/cbsd#54]
I put an fstab file in the $cbsd_root/jails-fstab directory, named as:

fstab.httpd

with the entries similar to:

/device/path   /mount/point    nullfs rw 0 0

and when I restarted cbsdd the file disappeared. So next, I stopped cbsdd, created the same file, and it disappeared when I started the daemon again. Puzzled, I created the file again, and this time only stopped the cbsdd daemon and same thing, the file disappeared!

In the meantime, I've just appended the entries to the host's /etc/fstab:

/device/path    $cbsd_root/jails-data/httpd-data/mount/point nullfs rw 0 0

to work around the issue, but I'm not sure what's wrong. Is the documentation correct? Do you have an example fstab.$jailname file that doesn't disappear for you? 
I ran a mkdir /path/to/httpd-data/mount/point before attempting any of this and each of the jails are base_rw

BTW: Sorry I'm such a pest :-P I really like cbsd and intend on using it from here out to manage my jails and eventually my VMs once I get a machine that will run the bhyve hypervisor. Thank you very much for your hard work!

**Comment by olevole** [comment]
You need use fstab with postfix .local for custom fstabs. E.g:

fstab.httpd.local

**Comment by jnbek** [comment]
Thanks!
