### ISSUE TITLE
Request - Make "cbsd node add" resolve DNS names.

### ISSUE THREAD

**Issue by mzs114** [olevole/cbsd#58]
In the current implementation we have to specify IP addresses while adding a node to CBSD.
It is helpful to use FQDN/Hostnames if they are already stored in `/etc/hosts` file or get the IP address by resolving it using the provided name servers in `/etc/resolv.conf`.

```
root@Zfreebsd:~ # cbsd node mode=add node=Zfreebsd8.my.domain port=22
Enter password of cbsd user on Zfreebsd8.my.domain: 
Can't resolv IP for Zfreebsd8.my.domain hostname. Use IP address.
```

**Comment by olevole** [comment]
Hmm. Look's like you use old CBSD version or Zfreebsd8.my.domain really have no records in DNS or /etc/hosts. Make sure that ' host Zfreebsd8.my.domain'  return IP addess, because CBSD use host(1) tools to get IP:

https://github.com/olevole/cbsd/blob/master/nodectl/node#L55
https://github.com/olevole/cbsd/blob/master/tools.subr#L61

**Comment by mzs114** [comment]
ok, the host exits in `/etc/hosts`:

```
root@Zfreebsd:~ # grep Zfree  /etc/hosts
192.168.56.8	Zfreebsd8 Zfreebsd8.my.domain

root@Zfreebsd:~ # ping Zfreebsd8
PING Zfreebsd8 (192.168.56.8): 56 data bytes
64 bytes from 192.168.56.8: icmp_seq=0 ttl=64 time=0.555 ms
^C
--- Zfreebsd8 ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.555/0.555/0.555/0.000 ms

root@Zfreebsd:~ # ping Zfreebsd8.my.domain
PING Zfreebsd8 (192.168.56.8): 56 data bytes
64 bytes from 192.168.56.8: icmp_seq=0 ttl=64 time=0.316 ms
64 bytes from 192.168.56.8: icmp_seq=1 ttl=64 time=0.281 ms
^C
--- Zfreebsd8 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.281/0.298/0.316/0.018 ms
```

But the node is not added:

```
root@Zfreebsd:~ # cbsd
cbsd@Zfreebsd> version
10.2.0

root@Zfreebsd:~ # cbsd node mode=add node=Zfreebsd8
Enter password of cbsd user on Zfreebsd8: 
Can't resolv IP for Zfreebsd8 hostname. Use IP address.

root@Zfreebsd:~ # cbsd node mode=add node=Zfreebsd8.my.domain
Enter password of cbsd user on Zfreebsd8.my.domain: 
Can't resolv IP for Zfreebsd8.my.domain hostname. Use IP address.
```

**Comment by olevole** [comment]
You're right. Indeed, the current method is not working for the /etc/hosts entries. The host(3) tools  only uses DNS. 
Unfortunately, I have not found a utility tool that can read /etc/hosts and DNS  records. We can use the gethostent/gethostbyname from libc. So, I implemented this in https://github.com/olevole/cbsd/commit/7bb54bc2e1fd588628f2398734deb0cc0f46757f  and it will work in the next release of CBSD. Thanks!
