### ISSUE TITLE
Problem updating firewall rules when changing NAT IP in cbsd initenv-tui

### ISSUE THREAD

**Issue by rodyaj** [olevole/cbsd#60]
Hi. Thanks for making cbsd. It is almost perfect for me, but for one possibe bug. When using `cbsd initenv-tui` to change the 'natip' property, the /usr/jails/etc/ipfw.conf  does not get updated with the new 'natip'. The workaround I've used is to change 'nat_enable' property to another firewall e.g., pf, press 'COMMIT'. then rerun `cbsd initenv-tui`, but this time switch 'nat_enable' property back to 'ipfw'. Pressing 'COMMIT' after this will update and source the '/usr/jails/etc/ipfw.conf' file properly.

**Comment by olevole** [comment]
Hi! I will look at this problem this weekend, thanks!

**Comment by mzs114** [comment]
Writing IPFW nat rules and stateful filtering rules is hard.. at last I moved to pf.
Hopefully FreeBSD developers update pf.

**Comment by rodyaj** [comment]
Yes I spent literally days getting my head around it. And I still don't know if I'm doing it right. There seems to be no consensus on the correct way.

**Comment by olevole** [comment]
Fixed within https://github.com/olevole/cbsd/commit/79c51fe942d512ce0e01d96eb8ace2caa3c0947c
