### ISSUE TITLE
Can CBSD support a dynamic host IP?

### ISSUE THREAD

**Issue by rodyaj** [olevole/cbsd#61]
Hi. The documentation says that the nodeip should be the:

> Working and static IP address of a node. It shouldn't be an alias

This is fine for most use cases, but not for mine, as I travel a lot with my laptop, and connect to many different wifi hotspots (work, home, hotel). This breaks the connectivity of my jails. So is it possible to use DHCP assigned IP with cbsd rather than static? That would save me the time of editing static IP in /etc/rc.conf and NAT rules (ipfw/pf) each time.

Or perhaps the nodeip is not essential to the jail management? Could I leave it blank, and just edit the NAT rules to use the wlan0 interface IP, rather than a static IP? I remember ipfw rules support the `to me` syntax to get the DHCP assigned IP of the interface. 

If this is not possible, would you consider adding a feature to cbsd to support roaming between locations through wifi with jails?

Thanks. I realise my use case is unusual, but I can't be the only one that uses jails on the move to test and develop. I'm sure some people could benefit from a roaming jail setup.

**Comment by olevole** [comment]
Hi!

"nodeip" must be static and it plays a role only if you have added one CBSD node to the other node ( via cbsd node mode=add ... )

in other cases (eg, local jails management) it is not essential.

So, if your jail have private (rfc1918) IP, but your laptop often gets a new address, all you have to do - is to enter a new IP address of node for NAT - rules forming and apply automatically:

This is two commands:
~~~
% cbsd natcfg     ( enter new IP )
% cbsd naton
~~~

Do I understand correctly that you're talking about the last example - you work only with local jail. And you want  to IP NAT was taked from specified interface automatically, instead of fixed/hardcoded IP?

**Comment by rodyaj** [comment]
Yes, you have correctly understood my issue. Using 'natcfg' and 'naton', I will make a script to set the natip from my DHCP assigned IP automatically. Or maybe I will just rewrite /usr/jails/etc/ipfw.conf to use 'to me' syntax.

Thanks.

**Comment by olevole** [comment]
it seems easy to implement: https://github.com/olevole/cbsd/commit/09c4a2514be3538dc39199a4a3f6eec339bf4ae4

natcfg now possible to specify not only IPv4 but also as network interface (re0, vtnet0, ..). 
The algorithm in this case is simple - on _naton_ stage, first IPv4 was taken on the interface as _natip_ ( This means that the IP must be initialized before CBSD starting)

At this point I'm assuming that a dynamic IP does not change during ONE system boot. 

In other words, if you move the running laptop between WiFi/hotspot networks or switch ethernet cable and issued a new IP address - you'll have to run the command **cbsd naton** every time.

You can test new changes by swithing from port version to github CBSD-current:

0) get git:
~~~
pkg install git
~~~

1) remove installed version of CBSD ( it is safe for jail data):
~~~
% pkg remove cbsd
~~~

2) If some files exist after removing in /usr/local/cbsd, remove it by hands:
~~~
rm -rf /usr/local/cbsd
~~~

3) Clone develop-version from GH:
~~~
git clone https://github.com/olevole/cbsd.git /usr/local/cbsd
~~~

4) Restore symlinks for bsdconfig module:
~~~
mkdir /usr/local/libexec/bsdconfig
ln -sf /usr/local/cbsd/share/bsdconfig/cbsd /usr/local/libexec/bsdconfig/cbsd
~~~

5) Restore rc.d script via symlink:
~~~
ln -sf /usr/jails/rc.d/cbsdrsyncd /usr/local/etc/rc.d/cbsdrsyncd
ln -sf /usr/jails/rc.d/cbsdd /usr/local/etc/rc.d/cbsdd
~~~
(where /usr/jails is workdir)

6) Upgrade CBSD code in your workdir from /usr/local/cbsd:
~~~
cbsd initenv
~~~

7) Clean object files in /usr/local/cbsd:
~~~
make -C /usr/local/cbsd clean
~~~

**Comment by rodyaj** [comment]
Thanks for taking the time to do this. I will test it tomorrow, as I am away from a computer right now. Your changes seem reasonable though.

**Comment by rodyaj** [comment]
Hi. I am trying to test this on a fresh freebsd install without cbsd, but cannot find the cbsd executable after cloning into /usr/local/cbsd and running 'make' with the required dependencies.

**Comment by olevole** [comment]
For fresh install you need repeat steps with 

% env workdir="/usr/jails" /usr/local/cbsd/sudoexec/initenv

See: http://www.bsdstore.ru/en/installing_cbsd.html#preparing

**Comment by rodyaj** [comment]
Yes sorry only just noticed the docs. Tested it and new nat feature works fine from bootup. Good work.

**Comment by olevole** [comment]
Excellent! I'll take it in the CBSD 10.3.0 release ( waiting for FreeBSD 10.3-RELEASE )
