### ISSUE TITLE
ddns

### ISSUE THREAD

**Issue by stelb** [olevole/cbsd#62]
I tried to configure ddns.
doing update with nsupdate works.

following the docs i tried this:

hostname is tomcat01.my.zone

   547  20:40   cbsd sysrc jname=tomcat01 ddns_zone_list="my_zone"
   549  20:41   cbsd sysrc jname=tomcat01 ddns_zones_my_zone="jail.my.zone"
   550  20:41   cbsd sysrc jname=tomcat01 ddns_key_my_zone="/usr/local/etc/namedb/keys/Kjail.+157+40074.private"

path to private key is on node host, not in target jail.

now following command failed:

# cbsd ddns jname=tomcat01 mode=add
Please set ddns_zone_list

this variable is set to my_zone.

Where did i miss something? docs broken? code broken?

Regards

**Comment by olevole** [comment]
Hi,

Indeed, the functionality is broken. I was planning to remove a note about DDNS site. Instead, it is better to use http://www.bsdstore.ru/en/10.2.0/wf_jconfig_ssi.html#execscript  - put nsupdate command, for example, in /usr/jails/jails-system/**$jname**/master_prestart.d/nsupdate.sh

If you want applied to all new jails,  you can use the template with http://www.bsdstore.ru/en/10.2.0/wf_profiles_ssi.html ( put nsupdate into custom /usr/jails/share/FreeBSD-jail-**$profile**-system-skel/ )

**Comment by stelb** [comment]
Hi Olev,

ok, thank you for the clarification and an alternative solution.
That took me sometime, starting with stupid on my side implementing ddns and than trying to understand how cbsd internals work.. .)

Regards
