### ISSUE TITLE
Error upgrading CBSD v.10.3.0

### ISSUE THREAD

**Issue by Jeroenski** [olevole/cbsd#65]
Hi,

Have an issue after upgrading to CBSD v.10.3.0. 

When i do `sudo cbsd initenv` I get `no workdir`. This does not change when I do `env workdir="/usr/jails" /usr/local/cbsd/sudoexec/initenv`.

When I do `cbsd help` I get `/usr/local/bin/cbsd: cpr: not found` and `Illegal option` See the attached file.

What can I do about this?

Thank you in advance.

J.

![cbsderror](https://cloud.githubusercontent.com/assets/17739878/13630643/a82a5a48-e5e0-11e5-99a9-ac5e8fc46fff.jpg)

**Comment by olevole** [comment]
Hi,

Error associated with cpr is not fatal - I'll fix it, thanks (this is old script which i forget to remove)

For **initenv/workdir**: Do I understand correctly that before CBSD did not work on this server?
Likely if you run it via sudo -  sudo is not configured to pass environment with "workdir" name.

Can you execute:
~~~
env workdir="/usr/jails" /usr/local/cbsd/sudoexec/initenv
~~~

from root user, without sudo ?

**Comment by Jeroenski** [comment]
Before CBSD worked correctly on this server. This issue is after upgrading from v 10.2.0. to .v 10.3.0.

I have executed (from root user, without sudo)

`env workdir="/usr/jails" /usr/local/cbsd/sudoexec/initenv`

than

`cbsd initenv`

still I get

`no workdir`

and also the `Illegal option` as above after `cbsd help`

**Comment by olevole** [comment]
According to https://github.com/olevole/cbsd/blob/master/sudoexec/initenv#L713:
~~~
if [ -z "${workdir}" ]; then
		. /etc/rc.conf
		if [ -n "${cbsd_workdir}" ]; then
			workdir="${cbsd_workdir}"
		else
			workdir="/usr/jails"
		fi
	fi
~~~

your rc.conf does not have **cbsd_workdir** variable. Please make sure that you have workdir in rc.conf:
~~~
grep ^cbsd_workdir /etc/rc.conf
~~~
should return cbsd_workdir="/usr/jails". If variable exist, send binary cbsd version and shell xtrace output:
~~~
1) 
% cbsd -c version
2)
% cbsd initenv --debug
3)
% truss cbsd
~~~

**Comment by Jeroenski** [comment]
/usr/jails is there

```
grep ^cbsd_workdir /etc/rc.conf
cbsd_workdir="/usr/jails"
```


```
uname -rm
10.1-RELEASE-p6 amd64
```
```

cbsd -c version
10.3.0


```

```
cbsd initenv --debug
no workdir
```

Attached you find the output of `truss cbsd`
[truss_cbsd.txt](https://github.com/olevole/cbsd/files/166874/truss_cbsd.txt)

**Comment by olevole** [comment]
Interesting.. a feeling that the sudo configuration does not pass **workdir** environment for cbsd user.
Can you check /usr/local/etc/sudoers.d/cbsd_sudoers ? It should look like this:
~~~
% cat /usr/local/etc/sudoers.d/cbsd_sudoers
Defaults     env_keep += "workdir DIALOG NOCOLOR CBSD_RNODE"
Cmnd_Alias   CBSD_CMD = /usr/jails/sudoexec/*,/usr/local/cbsd/sudoexec/*
cbsd   ALL=(ALL) NOPASSWD: CBSD_CMD
~~~

**Comment by Jeroenski** [comment]
The sudo configuration was not set. After setting the sudo configuration I do not get the `no workdir`-error anymore. 

Still have the `Illegal option --` and `/usr/local/bin/cbsd: cpr: not found` when I do `CBSD help`. This is  associated with cpr you mentioned?

**Comment by olevole** [comment]
**cpr: not found** solved by removing the line "cpr" from the file /usr/local/cbsd/securecmd and re-runing **cbsd initenv**. This is already done via https://github.com/olevole/cbsd/commit/e0c0294afa0f59304d9956cdfa897dd71ef2157e .
About "Illegal option --": this is known issue for me, but the reasons for this (and how it fix) is still unknown for me. I'm still in search of solutions.

**Comment by Jeroenski** [comment]
Ok. Thank you!

**Comment by olevole** [comment]
Fix illegal options: https://github.com/olevole/cbsd/commit/0cbfad7cd0d25bc97e78bf0e63ce03d464a90fce

Thanks.
