### ISSUE TITLE
presence of fstab.jname.local requires "substr" program

### ISSUE THREAD

**Issue by rhooper** [olevole/cbsd#67]
tools/mountfstab seems to require a "substr" tool that isn't installed by default for bare installs, nor specified as a dependency for cbsd.

I was following these instructions trying to get a zfs mount
https://www.bsdstore.ru/de/10.3/wf_jconfig_ssi.html

I created a `jails-fstab/fstab.services.local` with this entry:
```
tank/default/weblogs /var/log/weblogs zfs rw 0 0
```

and I get the following during startup (independent of allow_zfs config param):

```
# cbsd jstart services
NIC automatically selected: em0
Starting jail: services, parallel timeout=5
services: created
Setting hostname: services.local
ELF ldconfig path: /lib /usr/lib /usr/lib/compat /usr/local/lib
32-bit compatibility ldconfig path: /usr/lib32
Creating and/or trimming log files.
Starting syslogd.
Clearing /tmp (X related).
Updating motd:.
Performing sanity check on sshd configuration.
Starting sshd.
Starting cron.

Sat Mar 19 20:35:33 EDT 2016
/usr/jails/rcconf.subr: substr: not found
/usr/jails/rcconf.subr: substr: not found
/usr/jails/rcconf.subr: substr: not found
/usr/jails/rcconf.subr: substr: not found
/usr/jails/rcconf.subr: substr: not found
/usr/jails/rcconf.subr: cbsdjls: not found
attachzfs: jail is not running: services
jail: services: /bin/sh -c /usr/local/bin/cbsd attachzfs fstab=/usr/jails/jails-fstab/fstab.services.local jname=services; : failed
services: removed
```

This jail starts fine without fstab.services.local (or if I modify fstab.services directly ...)

**Comment by olevole** [comment]
Hi!

Thanks! This is bug in attachzfs script. **substr** is internal command in cbsd shell and this function is missing in /bin/sh. To fix this, please edit /usr/local/cbsd/tools/attachzfs script and change in first line **#!/bin/sh** to **#!/usr/local/bin/cbsd** than execute:
~~~
cbsd initenv
~~~

I've already fix this via https://github.com/olevole/cbsd/commit/4c7d40184a148c90df6006139095abbc81a1998c
