### ISSUE TITLE
Unable to turn nat off once enabled

### ISSUE THREAD

**Issue by LouPayne** [olevole/cbsd#70]
Doing a initenv-tui, you cannot turn off nat.  You can only select the 3 types of nat.

running cbsd natoff results in just stopping nat, but does not disable nat from being configured and starting back up when cbsdd is restarted or on system boot. 

The only way I found to be able to disable nat once it's been enabled is doing a:
cbsdsql local update local set nat_enable='0'

then rebooting machine.

**Comment by olevole** [comment]
Thank you. Good idea, I'll add a "nat off" option soon.

**Comment by olevole** [comment]
"Disable" option added via https://github.com/olevole/cbsd/commit/2c32c3f450c8cd144b74bd250aca18768a8c9378
