### ISSUE TITLE
MAC address conflict - vnet - jails

### ISSUE THREAD

**Issue by sslevil** [olevole/cbsd#73]
reproduce : 

create 3 jails using cbsd - and vnet networking
two of them got same mac address on internal eth0 vnet 

[1]

torrent:/root@[10:04] # ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
eth0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8<VLAN_MTU>
       ** ether 02:ff:70:00:08:0b**
     **   inet6 fe80::ff:70ff:fe00:80b%eth0 prefixlen 64 scopeid 0x2**
        inet 172.16.241.1 netmask 0xffff0000 broadcast 172.16.255.255
        inet6 xxxx:xxxx:xxxx::16:241:1 prefixlen 64
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
        status: active

[2]

download:/root@[10:10] # ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
eth0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8<VLAN_MTU>
      **  ether 02:ff:70:00:08:0b**
        inet6 fe80::ff:70ff:fe00:80b%eth0 **prefixlen 64 duplicated scopeid 0x2**
        inet 172.16.241.3 netmask 0xffff0000 broadcast 172.16.255.255
        inet6 xxxx:xxxx:xxxx::16:241:3 prefixlen 64
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
        status: active

Try to create another jail got again same mac address on internal eth0 , the host ifconfig looks god , each epair interface has unique mac address , only inside the jail got this issue . before cbsd i wass using iocage on same machine without encountering this problem , which could be the problem ?

Thanks , 

___________
Catalin M

**Comment by olevole** [comment]
Hi!

Yes, it unambiguously is a problem which needs to be corrected. However, it is impossible to me reprodice it. Can you show result from your master host output:
~~~
ifconfig |grep -A3 ^epair
~~~
when all vnet-jails is started?

Also, what method of creation jail ? 
I've try to create via jconstruct-tui: https://asciinema.org/a/dfxecwmmsvcug5g0x3mqm1lnt  and see normal behavior

**Comment by sslevil** [comment]
Hi ,

Thank you for your answer unfortunately cannot help you debug this further
because i just patch os kernel with "Temporary epair MAC address fix" -
https://github.com/lattera/freebsd/commit/624482876fe019bc1a74bfc3d6f690ac9bdf3196
which fix the issue. (
https://blog.plitc.eu/2014/freebsd-10-vimage-virtualized-network-stack-mit-if_bridge-epair/)
.

**Comment by olevole** [comment]
It seems that this patch or an analogue thereof is included in the FreeBSD-11 which i used in development ;-). Ok, I've just close this issue. Thanks for report.
