### ISSUE TITLE
help command leads to "Illegal option --" output

### ISSUE THREAD

**Issue by banym** [olevole/cbsd#75]
I am on version: cbsd-10.3.0 on a FreeBSD 10.3-RELEASE-p3
When I run cbsd help the output contains some "Illegal option --" errors

Here the output:

#cbsd help
basels  --  [build] List of bases
bclone  --  [bhyve] Jail cloning
bconfig  --  [bhyve] Configure for jail
Illegal option --
Illegal option --
Illegal option --
bconstruct-tui  --  [sys] Ncurses based Bhyve guest creation wizard
Illegal option --
Illegal option --
Illegal option --
bcontrol-tui  --  [jail] Ncurses based control for VM
bcreate  --  [bhyve] Create jail from config file
bexport  --  [jail] Export jail into image
bhyvedsk  --  [bhyve] Operate with bhyve disk images and databse
bhyvedsk-tui  --  [bhyve] Exec login into jail
bimport  --  [jail] Import jail from image
blogin  --  [bhyve] Exec login into jail
bls  --  [bhyve] List jail and status
border  --  [jail] List jail run order
Illegal option --
Illegal option --
Illegal option --
border-tui  --  [sys] Ncurses based VM order editor
bremove  --  [jail] Destroy jail
brename  --  [bhyve] Rename jail
bset  --  [bhyve] Modify parameter for jail
Illegal option --
Illegal option --
Illegal option --
bsetup-tui  --  [bhyve] Ncurses based setup for jail-arg
bstart  --  [bhyve] Start jail
bstop  --  [bhyve] Stop jail
buildkernel  --  [build] Build kernel from sources
buildworld  --  [build] Buildworld from sources
carpcfg  --  [sys] Enable CARP configuration
/usr/local/bin/cbsd: cpr: not found
cpr  --
ddns  --  [sys] Update DDNS records for jail
delete-old-libs  --  [sys] make delete-old and delete-old-libs for base
geli  --  [sys] cbsd geli helper
getnics-by-ip  --  [sys] Return network interface name by ip
help  --  [sys] This help
history  --  [sys] Show cbsd history command
initenv  --  Node re-initialization
Illegal option --
Illegal option --
Illegal option --
initenv-tui  --  [sys] Node re-initialization
installkernel  --  [build] Build kernel from sources
installworld  --  [build] Installbase from obj
j2prepare  --  [jail] Prepare remote node for accepting jail via j2slave
j2slave  --  [jail] Transfer jail as slave jail to remote node
jail2iso  --  [sys] Convert jail into cd9660 ISO or memstick image
jailmapdb  --  [sys] Return or update node for jail map
jbackup  --  [sys] Backup jail to slave node with slave status
jcleanup  --  [jail] Force unmount and cleanup for offline jail
jclone  --  [jail] Jail cloning
jcoldmigrate  --  [jail] Cold migrate (with save status) jail to remote node, set local jail as slave
jconfig  --  [jail] Configure for jail
jconstruct  --  [sys] console dialog for jail creation
Illegal option --
Illegal option --
Illegal option --
jconstruct-tui  --  [sys] Ncurses based jail creation wizard
Illegal option --
Illegal option --
Illegal option --
jcontrol-tui  --  [jail] Ncurses based control for jail
jcreate  --  [jail] Create jail from config file
jdescr  --  [jail] Show or modify jail description
jexec  --  [jail] Execution for command inside jail
jexport  --  [jail] Export jail into image
jget  --  [jail] Get info related to jail
jimport  --  [jail] Import jail from image
jlogin  --  [jail] Exec login into jail
jls  --  [jail] List jail and status
jmkrcconf  --  [jail] Create ascii rc.conf for jail
jmkrctlconf  --  [jail] Import or export from/to ascii rctl.conf from/to SQLite3 tables for jail
jorder  --  [jail] List jail run order
Illegal option --
Illegal option --
Illegal option --
jorder-tui  --  [sys] Ncurses based jail order editor
jrclone  --  [jail] Clone jail to remote machine
jrctl  --  [jail] Set or flush resource limit for jail
Illegal option --
Illegal option --
Illegal option --
jrctl-tui  --  [jail] Dialog based UI for RACCR/RCTL
jregister  --  [jail] Register jail records to SQLite from ASCii config or re-populate ASCii config from SQLite
jremove  --  [jail] Destroy jail
jrename  --  [jail] Rename jail
jrestart  --  [jail] jail jstop jstart sequence
jset  --  [jail] Modify parameter for jail
Illegal option --
Illegal option --
Illegal option --
jsetup-tui  --  [jail] Ncurses based setup for jail-arg
jsnapshot  --  [jail] Jail snapshot management
jstart  --  [jail] Start jail
jstatus  --  [jail] Return jail ID in output and jail existance as error code (0 -no jail, 1 - jail exist, 2 - slave)
jstop  --  [jail] Stop jail
jswmode  --  [jail] Jail switch mode between master/slave
junregister  --  [jail] Register jail records to SQLite from ASCii config or re-populate ASCii config from SQLite
jupgrade  --  [jail] Upgrade jail base data when baserw=1
jwhereis  --  [jail] Return node for jname
kernel  --  [build] Build kernel from sources
kernells  --  [sys] List of kernel
makejconf  --  [sys] Make jailv2 config file
makescene  --  [sys] Make jail by scenario file
mountfstab  --  [sys] Mount jail by fstab file
natcfg  --  [sys] Enable NAT service for RFC1918 Networks
natoff  --  [sys] Disable NAT service for RFC1918 Networks
naton  --  [sys] Enable NAT service for RFC1918 Networks
ndescr  --  [node] Show or modify node description
netinv  --  [sys] Update Network-related information in inventory tables
nlogin  --  [node] Login to remote node and/or exec command
node  --  [node] Manipulate or show information for remote nodes
portsup  --  [sys] Update FreeBSD ports tree in /usr/ports
objls  --  [build] List of object file
removebase  --  [build] Remove base dir
removekernel  --  [build] Remove base dir
removeobj  --  [sys] Remove obj-dir
removesrc  --  [sys] Remove src-dir
repo  --  [sys] Working with CBSD Repository
retrinv  --  [sys] Fetch sqldb from remote node
rexe  --  [sys] Execute remote command by ssh on the node
rsyncdoff  --  [sys] Disable RSYNC service for jail migration
rsyncdon  --  [sys] Enable RSYNC service for jail migration
srcls  --  [build] List of source
summary  --  [sys] Show summary statistics for the farm
srcpatch  --  [sys] Apply CBSD patch for FreeBSD source tree in
srcup  --  [sys] Update FreeBSD source tree in
sysinv  --  [sys] Collect and/or update system-related information in inventory tables
trafstat  --  [sys] Show traffic statistics for the jail
unmountfstab  --  [sys] Unmount jail by fstab file
upgrade  --  [sys] Upgrade base and/or kernel from other prepared hier
world  --  [build] Buildworld from sources + install world
zrep  --  [zrep] ZFS-snapshot-based replication for jail data
Illegal option --
Illegal option --
Illegal option --
vhidcfg-tui  --  [bhyve] Edit properties for vitual image of VM
Illegal option --
Illegal option --
Illegal option --
xconstruct-tui  --  [sys] Ncurses based Xen guest creation wizard
pkg  --  [helpers] cbsd pkg wrapper
tzsetup  --  [bsdconf] cbsd tzsetup wrapper
ssh  --  [bsdconf] OpenSSH jail helper
ftp  --  [bsdconf] Install timezone helper
adduser  --  [sys] Add user to jail
passwd  --  [bsdconf] cbsd passwd wrapper
service  --  [bsdconf] cbsd service wrapper
sysrc  --  [bsdconf] cbsd sysrc wrapper
userlist  --  [sys] Show user list
grouplist  --  [sys] Show group list
Illegal option --
Illegal option --
Illegal option --
adduser-tui  --  [bsdconf] Ncurses based dialog for jcreate
pw  --  [bsdconf] cbsd pw wrapper
zfsinstall  --  [helpers] mfsBSD ZFS install script

**Comment by olevole** [comment]
This issue already fixed via https://github.com/olevole/cbsd/commit/0cbfad7cd0d25bc97e78bf0e63ce03d464a90fce . Please fresh /usr/ports and update from sysutils/cbsd (looks like latest version still not available via pkg)

**Comment by banym** [comment]
Worked like a charm. Thx.
